# Generated by Django 4.2.30 on 2026-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("phone", "電話"),
                    ("email", "メール"),
                    ("line", "LINE"),
                    ("visit", "来訪"),
                    ("online", "訪問"),
                    ("other", "その他"),
                ],
                default="phone",
                max_length=20,
            ),
        ),
    ]
