# Generated by Django 4.2.30 on 2026-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contactlog_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("phone", "電話"),
                    ("email", "メール"),
                    ("line", "LINE"),
                    ("visit", "来訪"),
                    ("our_visit", "訪問"),
                    ("online", "オンライン"),
                    ("other", "その他"),
                ],
                default="phone",
                max_length=20,
            ),
        ),
    ]
