# Generated by Django 4.2.30 on 2026-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_up_threshold_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="最終接触日からこの日数以上経過した取引先を「要フォロー」として一覧に表示します。",
                        verbose_name="要フォロー判定日数",
                    ),
                ),
            ],
            options={
                "verbose_name": "システム設定",
                "verbose_name_plural": "システム設定",
            },
        ),
    ]
