# Generated by Django 4.2.30 on 2026-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_systemsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="取引先管理ID",
            ),
        ),
    ]
