# Generated by Django 4.2.30 on 2026-07-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_custom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="report_prompt_template",
            field=models.TextField(
                default="以下は{user_name}さんの{date}の接触記録です。\nこれをもとに、簡潔な日本語のビジネス日報を作成してください。\n\n# 接触記録\n{logs_text}\n\n# 出力フォーマット\n- 本日の活動概要\n- 対応した取引先一覧\n- 所感・課題\n",
                help_text="日報生成時にAIへ渡すプロンプトのテンプレートです。{user_name}・{date}・{logs_text}のプレースホルダーが使用できます。",
                verbose_name="日報生成プロンプト",
            ),
        ),
    ]
