# Generated by Django 4.2.30 on 2026-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="notified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="status",
            field=models.CharField(
                choices=[("ready", "完了"), ("pending", "生成中"), ("failed", "失敗")],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
