# Generated by Django 4.2.30 on 2026-07-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_dailyreport_error_message_dailyreport_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="regenerated",
            field=models.BooleanField(default=False),
        ),
    ]
