# Generated by Django 4.2.30 on 2026-07-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "ラベル", "verbose_name_plural": "ラベル"},
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "項目", "verbose_name_plural": "項目"},
        ),
    ]
